"""Dataset utilities.

Supports two CoNLL-style formats (auto-detected by column count):

  5-column  [generated by scripts/generate_dataset.py — preferred]
    word  identity_tag  location_tag  temporal_tag  domain_tag

  4-column  [standard CoNLL-2003: word pos chunk ner]
    Uses only the first and last columns; maps ner tag through conll_tag_to_ids.

Place your split files at:
  data/train.txt
  data/valid.txt
  data/test.txt
"""

import torch
from torch.utils.data import Dataset, DataLoader
from transformers import AutoTokenizer
from typing import Dict, List, Optional

from .labels import (
    conll_tag_to_ids,
    IDENTITY_TO_ID, LOCATION_TO_ID, TEMPORAL_TO_ID, DOMAIN_TO_ID,
)


class NERSample:
    __slots__ = ("words", "identity", "location", "temporal", "domain")

    def __init__(self, words, identity, location, temporal, domain):
        self.words    = words
        self.identity = identity
        self.location = location
        self.temporal = temporal
        self.domain   = domain


def read_conll(path: str) -> List[NERSample]:
    """Read CoNLL file; auto-detect 5-column (multi-head) or 4-column (CoNLL-2003)."""
    samples: List[NERSample] = []
    words, ident, loc, temp, dom = [], [], [], [], []

    with open(path, encoding="utf-8") as f:
        for raw in f:
            line = raw.strip()
            if not line or line.startswith("-DOCSTART-"):
                if words:
                    samples.append(NERSample(words, ident, loc, temp, dom))
                    words, ident, loc, temp, dom = [], [], [], [], []
                continue

            parts = line.split()
            word  = parts[0]

            if len(parts) == 5:
                # Multi-head format: word identity location temporal domain
                i = IDENTITY_TO_ID.get(parts[1], 0)
                l = LOCATION_TO_ID.get(parts[2], 0)
                t = TEMPORAL_TO_ID.get(parts[3], 0)
                d = DOMAIN_TO_ID.get(parts[4], 0)
            else:
                # CoNLL-2003 format: word [pos] [chunk] ner
                tag = parts[-1] if len(parts) >= 2 else "O"
                i, l, t, d = conll_tag_to_ids(tag)

            words.append(word);  ident.append(i)
            loc.append(l);       temp.append(t);  dom.append(d)

    if words:
        samples.append(NERSample(words, ident, loc, temp, dom))

    return samples


class GemmaNERDataset(Dataset):
    def __init__(self, samples: List[NERSample], tokenizer: AutoTokenizer, max_len: int = 128):
        self.items = [self._encode(s, tokenizer, max_len) for s in samples]
        self.items = [x for x in self.items if x is not None]

    @staticmethod
    def _encode(sample: NERSample, tokenizer: AutoTokenizer, max_len: int) -> Optional[Dict]:
        enc      = tokenizer(
            sample.words,
            is_split_into_words=True,
            truncation=True,
            max_length=max_len,
        )
        word_ids = enc.word_ids()

        def align(word_labels: List[int]) -> List[int]:
            prev = None
            out  = []
            for wid in word_ids:
                if wid is None:
                    out.append(0)               # special token → O
                elif wid == prev:
                    out.append(0)               # continuation subword → O
                else:
                    out.append(word_labels[wid])
                prev = wid
            return out

        return {
            "input_ids":      enc["input_ids"],
            "attention_mask": enc["attention_mask"],
            "identity_tags":  align(sample.identity),
            "location_tags":  align(sample.location),
            "temporal_tags":  align(sample.temporal),
            "domain_tags":    align(sample.domain),
        }

    def __len__(self):
        return len(self.items)

    def __getitem__(self, idx):
        return self.items[idx]


def collate_fn(batch: List[Dict]) -> Dict[str, torch.Tensor]:
    max_len = max(len(b["input_ids"]) for b in batch)

    def pad(seqs, val=0):
        return torch.tensor(
            [s + [val] * (max_len - len(s)) for s in seqs], dtype=torch.long
        )

    return {
        "input_ids":      pad([b["input_ids"]      for b in batch]),
        "attention_mask": pad([b["attention_mask"]  for b in batch]),
        "identity_tags":  pad([b["identity_tags"]   for b in batch]),
        "location_tags":  pad([b["location_tags"]   for b in batch]),
        "temporal_tags":  pad([b["temporal_tags"]   for b in batch]),
        "domain_tags":    pad([b["domain_tags"]     for b in batch]),
    }


def make_loader(samples, tokenizer, max_len, batch_size, shuffle=True) -> DataLoader:
    ds = GemmaNERDataset(samples, tokenizer, max_len)
    return DataLoader(ds, batch_size=batch_size, shuffle=shuffle, collate_fn=collate_fn)
